#ifndef OPCODE_ENUM_H
#define OPCODE_ENUM_H

#include "typeDefs.h"

enum e_opcode : uint16 {
	C_W_INIT = 1,
	S_W_INIT,
	C_W_CLOSE,
	S_W_CLOSE,
	S_W_PLAYER_ENTER_WORLD,
	S_W_PLAYER_LEAVE_WORLD,
	S_W_PLAYER_MOVE,
	C_W_PLAYER_ENTER_WORLD,
	C_W_PLAYER_LEAVE_WORLD,
	C_W_PLAYER_MOVE_BROADCAST,
	S_W_GET_VISIBLE_PLAYERS,
	C_W_GET_VISIBLE_PLAYERS,

	OP_MAX
};
#endif
